name: "AI Reviewer Buddy"
description: "This GitHub Action automatically reviews PRs using Google's Gemini AI model."
author: 'hoangnh'

inputs:
  GITHUB_TOKEN:
    description: 'GitHub token to interact with the repository'
    required: true
  GEMINI_API_KEY:
    description: 'Google Gemini API key'
    required: true
  AI_MODEL:
    description: 'The Gemini model to use for code review'
    required: false
    default: 'gemini-2.5-flash-preview-05-20'
  FILES_EXCLUDE:
    description: 'Comma-separated list of file patterns to exclude. Default excludes: *.md,*.txt,package-lock.json,pubspec.yaml,*.g.dart,*.freezed.dart,*.gr.dart,*.json,*.graphql'
    required: false
    default: ''
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install ai-pr-reviewer

    - name: Run AI PR Reviewer
      shell: bash
      env:
        GITHUB_API_URL: https://api.github.com
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_PULL_REQUEST_ID: ${{ github.event.pull_request.number }}
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        GEMINI_API_KEY: ${{ inputs.GEMINI_API_KEY }}
        AI_MODEL: ${{ inputs.AI_MODEL }}
        FILES_EXCLUDE: ${{ inputs.FILES_EXCLUDE }}
      run: ai-pr-reviewer github
