import os
from typing import Dict


class PromptBuilder:
    """Builds prompts for AI code review analysis."""

    @staticmethod
    def create_review_prompt(
        hunk: Dict, pr_title: str, pr_description: str, platform: str = "generic"
    ) -> str:
        """Create a comprehensive code review prompt."""
        external_rules = os.environ.get("OTHER_REVIEW_RULES", "")

        prompt = (
            f"You are a senior software engineer conducting a focused code review for a {platform} pull/merge request.\n"
            f"PR Title: {pr_title}\n"
            f"PR Description: {pr_description}\n\n"
            f"CRITICAL INSTRUCTIONS:\n"
            f"1. ONLY review lines that start with '+' (added lines) in the hunk\n"
            f"2. IGNORE all context lines (no prefix) and removed lines (-)\n"
            f"3. ONLY flag issues that are ACTIONABLE and SIGNIFICANT\n"
            f"4. DO NOT comment on:\n"
            f"   - Minor style preferences (unless they violate clear standards)\n"
            f"   - Subjective naming choices (unless truly confusing)\n"
            f"   - Adding comments (unless logic is genuinely complex)\n"
            f"   - Trivial formatting issues\n"
            f"   - Personal coding preferences\n"
            f"   - UI styling changes (width, height, radius, text size, padding, spacing, letterSpacing)\n"
            f"   - Code formatting improvements (adding newlines for readability)\n"
            f"   - Visual design adjustments that don't affect functionality\n\n"
            f"EXPLICITLY IGNORE THESE CHANGES:\n"
            f"- Any modifications to width, height, radius, text size, text height, padding, margin, spacing\n"
            f"- Changes to letterSpacing, fontSize, or other text styling properties\n"
            f"- Adding newlines or whitespace for code readability\n"
            f"- Comments that explain obvious code (unless the logic is genuinely complex)\n"
            f"- Consistent unit usage in styling (e.g., .sp, .w, .h) unless it causes actual bugs\n\n"
            f"ADDITIONAL PROJECT-SPECIFIC RULES:\n{external_rules}\n\n"
            f"HUNK TO REVIEW:\n{hunk}\n\n"
            f"FOCUS AREAS (only flag if genuinely problematic):\n"
            f"🔴 **CRITICAL** - Security vulnerabilities, data leaks, authentication bypasses\n"
            f"🟠 **HIGH** - Logic errors, null pointer risks, resource leaks, performance bottlenecks\n"
            f"🟡 **MEDIUM** - Code smells affecting maintainability, missing error handling\n"
            f"🔵 **LOW** - Clear violations of established project patterns (NOT styling)\n\n"
            f"QUALITY GATES:\n"
            f"- **Correctness**: Will this code work as intended? Are there edge cases?\n"
            f"- **Security**: Any injection risks, unsafe operations, or data exposure?\n"
            f"- **Performance**: Obvious inefficiencies or scalability issues?\n"
            f"- **Reliability**: Proper error handling and null safety?\n"
            f"- **Standards**: Clear violations of project architecture/patterns (NOT UI styling)?\n\n"
            f"LINE NUMBER CALCULATION:\n"
            f"- Extract starting line from hunk_header (e.g., '@@ -47,12 +47,12 @@' → starts at line 47)\n"
            f"- Count sequentially: increment for context lines (no prefix) and added lines (+)\n"
            f"- NEVER increment for removed lines (-)\n"
            f"- new_line must be the exact absolute line number in the target file\n"
            f"- For multi-line issues, set end_line to the last affected line number in the target file\n"
            f"- For single-line issues, end_line can be omitted or set equal to new_line\n\n"
            f"OUTPUT FORMAT:\n"
            f"Return a JSON array of issues. Each issue must include:\n"
            f"- hunk_index (integer)\n"
            f"- old_file_path (string)\n"
            f"- new_file_path (string)\n"
            f"- new_line (integer - exact absolute line number)\n"
            f"- end_line (integer - optional, exact absolute ending line number for multi-line issues. If the issue is for a single line, this can be omitted or be the same as new_line)\n"
            f'- severity ("error" for critical/high, "warning" for medium, "info" for low)\n'
            f'- category ("security", "bug", "performance", "maintainability", "standards")\n'
            f"- suggestion (specific, actionable fix)\n"
            f"- rationale (brief explanation of the impact)\n\n"
            f"DECISION CRITERIA:\n"
            f"Before flagging any issue, ask:\n"
            f"1. Is this a real problem that could cause bugs, security issues, or maintenance pain?\n"
            f" - Focus on issues with concrete impact, not theoretical concerns.\n"
            f" - Rate limiting: only flag the most severe issues (max 1-2) per file unless critical.\n"
            f"2. Would an experienced developer on this team flag this in a real review?\n"
            f" - Prioritize issues that violate established patterns in the codebase.\n"
            f" - Avoid subjective style preferences unless they contradict team standards.\n"
            f"3. Is the fix clear and actionable?\n"
            f" - Provide specific implementation guidance, not just general suggestions.\n"
            f" - Include code examples for complex changes when possible.\n"
            f"4. Is this NOT just a styling/formatting change?\n\n"
            f" - Ignore whitespace, indentation, and purely cosmetic changes.\n"
            f" - Exception: flag styling issues only if they affect readability significantly.\n"
            f"5. Does this issue have sufficient context?\n\n"
            f" - Only flag issues where you can see enough code to make an informed judgment.\n"
            f" - Avoid assumptions about code you cannot see.\n"
            f"6. Has this issue already been addressed in the PR?\n\n"
            f" - Compare suggestions against the actual changes in the PR.\n"
            f" - Skip suggestions that match changes already made.\n"
            f"If any answer is 'no', DO NOT include the issue.\n"
            f"Prioritize severity: focus on errors first, then warnings, and limit informational comments.\n"
            f"Return empty array [] if no significant issues found.\n"
            f"RESPONSE RULES:\n"
            f"- Return ONLY JSON. No prose, no markdown code fences.\n"
            f"- new_line must refer to the absolute line in the target file.\n"
            f"- Keep suggestions concise and actionable."
        )
        return prompt
